site_name: JACoW - Running an IPAC
#site_url: https://docs-IPAC.JACoW.org
theme: material
repo_name: 'jacow-org/docs-IPAC'
repo_url: 'https://github.com/jacow-org/docs-IPAC'
nav:
  - Introduction: index.md
  - Glossary: glossary.md 
  - Organising Committees: committees.md
  - General instructions:
    - How to login to the Indico event: General/JACoWlogin.md
  - Delivery and Initial Setup - Admin:
    - Access to new event: InitialSetup/intro.md
    - Management area: 
      - Settings, Timetable, Protection: InitialSetup/mgmt_area_01.md
      - Organization: InitialSetup/mgmt_area_02.md
      - Workflows: InitialSetup/mgmt_area_03.md
      - Reports: InitialSetup/mgmt_area_04.md
      - Customization: InitialSetup/mgmt_area_05.md
  - Invited Oral Presentations:
    - Introduction: InvitedOrals/intro.md
    - Scientific Secretariat/Admin: 
      - Intial Setup: InvitedOrals/SSsetup.md
      - How submission will work: InvitedOrals/SSsubmission.md
      - Call for Proposals for Invited Oral Presentations: InvitedOrals/SScall.md
      - Post submission duties: InvitedOrals/SSpostsubmit.md
      - Abstract Initial QA: InvitedOrals/SSinitialQA.md
      - Setups for the SPC review: InvitedOrals/SSSPCsetup.md
      - Creating sessions and assigning programme codes: InvitedOrals/SSpcodes.md
      - Publishing the programme: InvitedOrals/SSpublishing.md
      - Invitation to invited speakers: InvitedOrals/SSinviteinvited.md
      - Tips and tricks: InvitedOrals/SStipsandtricks.md
    - SPC/OC/SAB:
      - Submission of Proposals for Invited Oral Presentations: InvitedOrals/SABsubmission.md
      - "SPC: proposal of track changes": InvitedOrals/SPCtrackreview.md
      - "SPC MC Coordinators: review tracks": InvitedOrals/MCCtrackreview.md
      - "SPC: give priority to proposals": InvitedOrals/SPCprioritization.md
      - "SPC MC Coordinators: accept proposals": InvitedOrals/MCCaccept.md
  - Contributed Abstracts:
    - How to submit an abstract: ContributedAbstracts/submission.md
  - Abstract Booklet:
    - Mail Merge to RTF: AbstractBooklet/MailMerge.md

